name: Fetch Data

on:
   schedule:
    - cron: "0 18 * * *"
   workflow_dispatch:

env:
  S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUDGET_ID: ${{ secrets.BUDGET_ID }}
  YNAB_API_KEY: ${{ secrets.YNAB_API_KEY }}

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install requirements
        run: pip install -r data/requirements.txt
      - name: Fetch data
        run: python data/ynab.py
